version: '3.8'

services:
  nginx:
    build:
      context: ./deployments/nginx
      dockerfile: Dockerfile
    container_name: nginx_gateway
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-v1
      - api-v2
    networks:
      - mlops-network

  api-v1:
    build:
      context: ./src/api
      dockerfile: v1/Dockerfile
    deploy:
      replicas: 3   # 3 replicas for load balancing
    volumes:
      - ./model/model.joblib:/app/model.joblib:ro
    networks:
      - mlops-network

  # debug version
  api-v2:
    build:
      context: ./src/api
      dockerfile: v2/Dockerfile
    container_name: api-v2
    volumes:
      - ./model/model.joblib:/app/model.joblib:ro
    networks:
      - mlops-network

  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx_exporter
    command:
      - '-nginx.scrape-uri=http://nginx_gateway:80/nginx_status'
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - mlops-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_server
    ports:
      - "9090:9090"
    volumes:
      - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - nginx_exporter
    networks:
      - mlops-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deployments/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./deployments/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./deployments/grafana/dashboards:/etc/grafana/dashboards:ro
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_INSTALL_PLUGINS=
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
